config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :posts

root :to=> "posts#index"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true


  has_attached_file :image, style: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
        # :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


def index
		@posts = Post.all.order('created_at DESC')
	end

	def show
		@post = Post.find(params[:id])
		@posts = Post.order("created_at desc").limit(4).offset(1)
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jaset Construction Co.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-G3Fme2BM4boCE9tHx9zHvcxaQoAkksPQa/8oyn1Dzqv7gdcXChereUsXGx6LtbqA" crossorigin="anonymous">

<script src="https://stackpath.bootstrapcdn.com/bootlint/0.16.7/bootlint.min.js" integrity="sha384-3T50BVAepXDP+/77qijxE3Yj8K/jaICuCvy27UZhXdMymNl/ojOww5yJKFINHsvK" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/745dfbbd77.js" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

  </head>

  <body>
<%= render 'shared/header' %>
<%= render 'shared/alerts' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/assets/2.png" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/3.png" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/1.png" alt="Third slide">
    </div>
  </div>
</div>




<!-- Portfolio Grid Section -->
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Portfolio</h2>
                
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
                <% @posts.each do |post| %>
                <div class="col-sm-4 portfolio-item">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image.url, class: 'img-responsive' %>
                <% end %>
                </div>
            <% end %>
        </div>
    </div>
</section>

<div class="skew-c"></div>



 <!-- About -->
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">About</h2>
          <h3 class="section-subheading text-muted">Think Construction! Think Jaset!</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <ul class="timeline">
            <li>
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/assets/01.png" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">  
                  <h4>The Journey</h4>
                  <h4 class="subheading">Organisation Structure</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">Jaset Construction Company Limited has headquarters in Nairobi, Kenya and has a staff compliment of twenty people stationed in Nairobi. The company is organised in to 4 main Departments<br>
                   1.Management team<br>
                   2.Procurement team <br>
                   3.Project management team<br>
                   4.Administration and Finance team <br>
                    divisions which are later branched to the minor divisions (planning and project operations).</p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/assets/02.png" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>The Journey</h4>
                  <h4 class="subheading">Genesis</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">Jaset Construction Company limited was launched in 2008 after running as a partnership by the name of Jaset general contractors, and is a professional company addressed to building, construction and all civil engineering works, with solutions in the areas of design, construction and urban development. Over the years the company has undertaken many challenging projects and accumulated skills, know-how and experiences in design and building solutions, management services and related engineering works..</p>
                </div>
              </div>
            </li>
            <li>
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/assets/03.png" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>The Journey</h4>
                  <h4 class="subheading">Services</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted"></br>We are specialists in:<br>
    • High rise buildings.<br>
    • Bungalows and massionates.<br>
    • Sewerage system works.<br>
    • Roads and Parking.<br>
    • Among others</p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-image">
                <img class="rounded-circle img-fluid" src="/assets/04.png" alt="">
              </div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4>The Journey</h4>
                  <h4 class="subheading">Our Speciality</h4>
                </div>
                <div class="timeline-body">
                  <p class="text-muted">Today, Jaset Construction Company takes on the role of main contractor for small to medium 
Size projects, providing the client with an “I am assured “experience when we are chosen to execute the project. We ensure that client’s objectives are top priority in the planning and execution of all our processes.
The Company has a staff committed to running the four business units as the core for our company namely: <br>
    1) Consultancy and advice.<br>
    2) Engineering and Construction.<br>
    3) Administration and project management.<br>
    4) Maintenance of built facilities.</p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-image">
                <h4>Be Part
                  <br>Of Our
                  <br>Story!</h4>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>



<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><%= mail_to "info@jasetconstruction.co.ke", "Contact Us", subject: "Hi! Please include your name and email address" %></h2><br>
                <hr class="star-primary">
            </div>
        </div>
</section>





<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>






 

app/views/posts/show.html.erb
<!-- Page Content -->
<div class="container post-container">

    <!-- Portfolio Item Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%= @post.title %>
                <small>Portfolio</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <%= image_tag @post.image.url, class: 'img-responsive' %>
        </div>

        <div class="col-md-4">
            <h3>Project Description</h3>
            <p><%= @post.body %></p>
        </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <div class="row">

        <div class="col-lg-12">
            <h3 class="page-header">Related Projects</h3>
        </div>

        <% @posts.each do |post| %>
            <div class="col-sm-3 col-xs-6">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image.url, class: 'img-responsive portfolio-item' %>
                <% end %>
            </div>
        <% end %>

    </div>
    <!-- /.row -->

<%= link_to 'Back', posts_path %>


</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">

        <!-- Footer Location -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Location</h4>
          <p class="lead mb-0">Mfangano Trade Centre
            <br>4th Floor
            <br>Nairobi, Kenya
           
            </p>
        </div>


 <!-- Footer Social Icons -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Around the Web</h4>
          <a class="btn btn-outline-light btn-social mx-1" target="_blank" href="https://www.facebook.com/jasetconstruction">
            <i class="fab fa-fw fa-facebook-f"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1"  target="_blank" href="https://twitter.com/">
            <i class="fab fa-fw fa-twitter"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" target="_blank" href="https://www.linkedin.com/in/jaset-construction-company-ltd-18a8522a">
            <i class="fab fa-fw fa-linkedin-in"></i>

          </a>
          <br>
         <br> 0719-873-406
         <br> 0728-227-399

        </div>


    
        <!-- Footer About Text -->
        <div class="col-lg-4">
          <h4 class="text-uppercase mb-4">About Jaset Construction Company</h4>
          <p class="lead mb-0"> We are a company that takes pride in our delivery, thus our clients can always be assured that only the most experienced and qualified people are serving them all the time, consequently the goodwill of those we serve is the foundation of our success.</p>

        </div>

      </div>
    </div>




  </footer>
    <!-- Copyright Section -->
  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy;Jaset Construction Company Limited 2020</small>
    </div>
  </section>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  

  <div class="nav-item">


  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
<a class="navbar-brand"<%=  link_to "Jaset Construction Company", :controller => "posts", :action => "index" %> <i class="fas fa-hard-hat"></i>  </a>
    </li>
    </ul> 
  </div>

  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-hard-hat"></i>
      </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#portfolio">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#contact">Contact</a>
      </li>
    </ul> 
  </div>
</nav>